apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gen-ai-frontend-route
spec:
  to:
    kind: Service
    name: gen-ai-frontend-svc
  port:
    targetPort: 5173
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None