name: Build and Push Docker image (main branch only)

on:
  push:
    branches:
      - playwright-ci

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build and run Backend
        working-directory: ./gen-ai-playground/backend
        run: |
          docker build -t ghcr.io/${{ env.OWNER_LC }}/fastapi-backend:latest .
          docker run -d -p 8000:8000 --name backend ghcr.io/${{ env.OWNER_LC }}/fastapi-backend:latest
          sleep 3
          docker ps -a
          docker logs backend || true

      - name: Build and run Frontend
        working-directory: ./gen-ai-playground/frontend
        run: |
          docker build . --tag ghcr.io/${{ env.OWNER_LC }}/vite-frontend:latest
          docker run -d -p 5173:5173 --name frontend ghcr.io/${{ env.OWNER_LC }}/vite-frontend:latest
          sleep 3
          docker ps -a
          docker logs frontend || true


      - name: Wait for backend
        run: npx wait-on http://localhost:8000/docs

      - name: Wait for frontend
        run: npx wait-on http://localhost:5173

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run eslint
        working-directory: ./gen-ai-playground/frontend
        run: npm run lint

      - name: Push Backend image
        working-directory: ./gen-ai-playground/backend
        run: docker push ghcr.io/${{ env.OWNER_LC }}/fastapi-backend:latest

      - name: Push Frontend image
        working-directory: ./gen-ai-playground/backend
        run: docker push ghcr.io/${{ env.OWNER_LC }}/vite-frontend:latest


      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30